### ISSUE TITLE
enable-librtmp option is harmful?

### ISSUE THREAD

**Issue by trengri** [negativo17/ffmpeg#11]
When writing to rtmp:// output, ffmpeg terminates after 30-40 minutes with the following error:
```
av_interleaved_write_frame(): End of file
```
This appears to be the following bug: https://trac.ffmpeg.org/ticket/7547
Currently ffmpeg is built with `--enable-librtmp` option, which makes use of `librtmp`. Recommended workaround is to build without `--enable-librtmp` option as ffmpeg has native RTMP implementation.

Is it possible to remove `--enable-librtmp` option from SPEC file? It's not enabled by default and I believe this option is harmful as native RTMP implementation works fine.

**Comment by scaronni** [comment]
Ah cool, was not aware of it. Will push an update without the library.

Thanks!
