### ISSUE TITLE
Consider only providing the libavcodec-freeworld overlay library package

### ISSUE THREAD

**Issue by Conan-Kudo** [negativo17/ffmpeg#12]
Since Fedora now provides a reasonably complete ffmpeg implementation modulo a few encumbered codecs, would you consider restructuring your package to produce only an overlay library for the ffmpeg implementation in Fedora? That way we don't need to play EVR games and users can easily leverage your package on top of Fedora without fuss.

**Comment by scaronni** [comment]
Hi Nael, I'm not sure I understand. `libavcodec` is just a small fraction, I'm including the Handbrake patches and I'm doing the same with all the other libraries, I replacing `gstreamer1-plugins*` packages, link them with unredistributable libraries. etc. Most of the time I have a newer epoch as well to avoid issues, so there should be no EVR games to play.

I have no issues changing stuff if the need arise, but can you elaborate a bit on it? So far I did not push for anyone to use this repository, it mostly comes out of personal and work related stuff.

**Comment by Conan-Kudo** [comment]
I see. I hadn't quite realized that. My request doesn't make sense then. Sorry for the noise.

**Comment by scaronni** [comment]
No worries. I thought you had something else in mind. I'm open to make changes if needed.

Thanks.
