### ISSUE TITLE
conflicts with epel

### ISSUE THREAD

**Issue by pgera** [negativo17/ffmpeg#2]
Seeing this today:
Error: Package: 1:ffmpeg-libs-3.4-1.el7.x86_64 (epel-multimedia)
           Requires: libmp3lame.so.0()(64bit)
           Removing: lame-libs-3.99.5-8.el7.x86_64 (@epel)
               libmp3lame.so.0()(64bit)
           Updated By: lame-libs-3.100-1.el7.i686 (epel-multimedia)
               Not found

**Comment by scaronni** [comment]
`lame-libs-3.100-1.el7` is still in `epel-testing` but it will reach stable soon:
https://bodhi.fedoraproject.org/updates/?packages=lame

For the next days you can just do:

`yum --enablerepo=epel-testing update lame-libs`

**Comment by pgera** [comment]
Thanks. Works.
