### ISSUE TITLE
[RHEL 7.5] ffmpeg-libs package conflict 

### ISSUE THREAD

**Issue by justwheel** [negativo17/ffmpeg#3]
I tried to install `ffmpeg` today on a RHEL 7.5 workstation. However, there is a dependency issue with `libbluray`.

```
$ sudo yum install ffmpeg
…
Error: Package: 1:ffmpeg-libs-4.0-3.el7.x86_64 (epel-multimedia)
           Requires: libbluray.so.2()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

I assume it is a RHEL 7.5 support issue. I'm not sure what is necessary to resolve this. If I can provide any debug info, please let me know.

**Comment by scaronni** [comment]
Hello, the dependencies are fine:

```
# rpm -q --requires ffmpeg-libs | grep libbluray
libbluray.so.2()(64bit)
# repoquery --whatprovides "libbluray.so.2()(64bit)"
libbluray-0:1.0.2-2.el7.x86_64
```
Which is in the repository:

https://negativo17.org/repos/multimedia/epel-7/x86_64/libbluray-1.0.2-2.el7.x86_64.rpm

Can you post the entire output?

**Comment by justwheel** [comment]
@scaronni I didn't look closely enough. It was a subtle dependency problem with a package of the same name but older version. Closing this issue, I was able to install ffmpeg.
