### ISSUE TITLE
Version 4.0.1 broke alsa support

### ISSUE THREAD

**Issue by xadhoom** [negativo17/ffmpeg#4]
While version 4.0-3 works ok (installed in May)

With latest ffmpeg, it exits with `"Unknown input format: 'alsa'`

Seems that a `BuildRequires:  alsa-lib-devel` should be added into spec?

**Comment by scaronni** [comment]
Oh! Good catch. It has never been there, it was probably pulled in by something else. Will push an update along with other changes soon.

**Comment by scaronni** [comment]
https://github.com/negativo17/ffmpeg/commit/6490697ebe471e9cb39c9c717208c4bcc0624540
