### ISSUE TITLE
Request: support dash demuxer by building against libxml2

### ISSUE THREAD

**Issue by barsnick** [negativo17/ffmpeg#5]
Please build ffmpeg with the configure option "--enable-libxml2", and with a BuildRequires of libxml2-devel.

This is really low hanging fruit, allowing ffmpeg to natively support demuxing dash URIs, which are becoming ever more popular. (No other ffmpeg features are currently enabled or enhanced by this dependency.)

Thanks again for your very practical builds/repo!

**Comment by scaronni** [comment]
Back from holiday. Done, thanks for reporting:
https://github.com/negativo17/ffmpeg/commit/aa8c178a34e57ac88020e23f92a1516dd3f06877
New build coming tomorrow.
